# Docker Compose Version - unrelated to project
version: "3"

#? Define your services here
services:

  #? The reverse proxy
  proxy:
    image: stories-nginx-dev
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    networks:
      - subnet
    depends_on:
      - frontend

  #? Stories Application
  frontend:
    image: stories-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ENV: develop
    depends_on:
      - db
    networks:
      - subnet
    volumes:
      - ./app:/usr/src/stories/app
      - ./logs:/usr/src/stories/logs
      - ./migrations:/usr/src/stories/migrations

  #? PostgreSQL database
  db:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: stories
    ports:
     - "5442:5432"
    networks:
      - subnet
    volumes:
      - db_data:/var/lib/postgresql/data

#? Your Networks
networks:
  subnet:

#? Your Volumes
volumes:
  db_data: