branch-defaults:
  master:
    environment: stage
    group_suffix: null
global:
  application_name: covid-publishing-api
  branch: null
  default_platform: Docker 18.09.9-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
