version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
        command: |
          pipenv run python -m pytest
      - store_test_results:
          path: test-results
