version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql
      - checkout
      - run: pipenv run pip install -r requirements.txt
      - run:
          name: run pytest
          command: |
            mkdir test-results
            pipenv run python -m pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results
