version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: pipenv run pip install -r requirements.txt
      - run: pipenv run python -m pytest
