version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_HOST=127.0.0.1
          DATABASE_NAME=test
          DATABASE_PORT=5432
          DATABASE_USER=postgres
          DATABASE_PASS=postgres
    steps:
      - checkout
      - run: pipenv run pip install -r requirements.txt
      - run: pipenv run python -m pytest
