version: 2.1

workflows:
  version: 2.1
  test:
    jobs:
      - unit_test
      - build_and_test_docker

jobs:
  unit_test:
    docker:
      - image: circleci/python:3.6.9
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_HOST: 127.0.0.1
          DATABASE_NAME: test
          DATABASE_PORT: 5432
          DATABASE_USER: postgres
          DATABASE_PASS: postgres
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql
      - checkout
      - run: pipenv run pip install -r requirements.txt
      - run:
          name: run pytest
          command: |
            mkdir test-results
            pipenv run python -m pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results

  build_and_test_docker:
    machine: true
    steps:
      - checkout
      - run: docker build -t covpubapi .
      - run: docker run covpubapi
