"""add new fields from data dictionary

Revision ID: 01f76bf60f51
Revises: ee1eae7d2f16
Create Date: 2020-05-27 00:41:28.290814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f76bf60f51'
down_revision = 'ee1eae7d2f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('antibodyNegative', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('antibodyPositive', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('antibodyTotal', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('deathConfirmed', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('deathProbable', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('pcrNegativeTests', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('pcrPositiveCases', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('pcrPositiveTests', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('pcrTotalTests', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('positiveConfirmed', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('totalTestsPeople', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coreData', 'totalTestsPeople')
    op.drop_column('coreData', 'positiveConfirmed')
    op.drop_column('coreData', 'pcrTotalTests')
    op.drop_column('coreData', 'pcrPositiveTests')
    op.drop_column('coreData', 'pcrPositiveCases')
    op.drop_column('coreData', 'pcrNegativeTests')
    op.drop_column('coreData', 'deathProbable')
    op.drop_column('coreData', 'deathConfirmed')
    op.drop_column('coreData', 'antibodyTotal')
    op.drop_column('coreData', 'antibodyPositive')
    op.drop_column('coreData', 'antibodyNegative')
    # ### end Alembic commands ###
