"""empty message

Revision ID: 0c6db53f2db2
Revises: 62a65242ccf3
Create Date: 2020-06-26 17:55:26.309606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6db53f2db2'
down_revision = '62a65242ccf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('negativeTestsViral', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('positiveCasesViral', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('positiveTestsViral', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('totalTestsViral', sa.Integer(), nullable=True))
    op.drop_column('coreData', 'pcrNegativeTests')
    op.drop_column('coreData', 'pcrPositiveTests')
    op.drop_column('coreData', 'pcrTotalTests')
    op.drop_column('coreData', 'pcrPositiveCases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('pcrPositiveCases', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coreData', sa.Column('pcrTotalTests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coreData', sa.Column('pcrPositiveTests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coreData', sa.Column('pcrNegativeTests', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('coreData', 'totalTestsViral')
    op.drop_column('coreData', 'positiveTestsViral')
    op.drop_column('coreData', 'positiveCasesViral')
    op.drop_column('coreData', 'negativeTestsViral')
    # ### end Alembic commands ###
