"""Add additional state columns

Revision ID: 0d412b939e30
Revises: 51fcfb4b5daa
Create Date: 2020-05-18 23:03:54.641232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d412b939e30'
down_revision = '51fcfb4b5daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('covid19Site', sa.String(), nullable=True))
    op.add_column('states', sa.Column('covid19SiteOld', sa.String(), nullable=True))
    op.add_column('states', sa.Column('covid19SiteSecondary', sa.String(), nullable=True))
    op.add_column('states', sa.Column('fips', sa.String(), nullable=True))
    op.add_column('states', sa.Column('name', sa.String(), nullable=True))
    op.add_column('states', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('states', sa.Column('pui', sa.String(), nullable=True))
    op.add_column('states', sa.Column('pum', sa.Boolean(), nullable=True))
    op.add_column('states', sa.Column('twitter', sa.String(), nullable=True))
    op.drop_column('states', 'fullName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('fullName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('states', 'twitter')
    op.drop_column('states', 'pum')
    op.drop_column('states', 'pui')
    op.drop_column('states', 'notes')
    op.drop_column('states', 'name')
    op.drop_column('states', 'fips')
    op.drop_column('states', 'covid19SiteSecondary')
    op.drop_column('states', 'covid19SiteOld')
    op.drop_column('states', 'covid19Site')
    # ### end Alembic commands ###
