"""empty message

Revision ID: 3082b0c488cf
Revises: 595ca88a92f4
Create Date: 2020-06-10 15:06:11.965388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3082b0c488cf'
down_revision = '595ca88a92f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('dataQualityGrade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coreData', 'dataQualityGrade')
    # ### end Alembic commands ###
