"""Adding two more screenshot URLs to States

Revision ID: 41ab3d22f073
Revises: 6dd1f6208644
Create Date: 2020-09-25 14:24:37.753379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ab3d22f073'
down_revision = '6dd1f6208644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('covid19SiteQuaternary', sa.String(), nullable=True))
    op.add_column('states', sa.Column('covid19SiteQuinary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'covid19SiteQuinary')
    op.drop_column('states', 'covid19SiteQuaternary')
    # ### end Alembic commands ###
