"""Adding initial tables

Revision ID: 51fcfb4b5daa
Revises: 
Create Date: 2020-05-09 19:12:12.214138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fcfb4b5daa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('batchId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publishedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shiftLead', sa.String(length=100), nullable=True),
    sa.Column('batchNote', sa.String(), nullable=True),
    sa.Column('dataEntryType', sa.String(), nullable=True),
    sa.Column('isPublished', sa.Boolean(), nullable=False),
    sa.Column('isRevision', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('batchId')
    )
    op.create_table('states',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('coreData',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('batchId', sa.Integer(), nullable=False),
    sa.Column('positive', sa.Integer(), nullable=True),
    sa.Column('negative', sa.Integer(), nullable=True),
    sa.Column('pending', sa.Integer(), nullable=True),
    sa.Column('hospitalizedCurrently', sa.Integer(), nullable=True),
    sa.Column('hospitalizedCumulative', sa.Integer(), nullable=True),
    sa.Column('inIcuCurrently', sa.Integer(), nullable=True),
    sa.Column('inIcuCumulative', sa.Integer(), nullable=True),
    sa.Column('onVentilatorCurrently', sa.Integer(), nullable=True),
    sa.Column('onVentilatorCumulative', sa.Integer(), nullable=True),
    sa.Column('recovered', sa.Integer(), nullable=True),
    sa.Column('death', sa.Integer(), nullable=True),
    sa.Column('privateNotes', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('lastUpdateTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lastCheckTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('checker', sa.String(length=100), nullable=True),
    sa.Column('doubleChecker', sa.String(length=100), nullable=True),
    sa.Column('publicNotes', sa.String(), nullable=True),
    sa.Column('sourceNotes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batchId'], ['batches.batchId'], ),
    sa.ForeignKeyConstraint(['state'], ['states.state'], ),
    sa.PrimaryKeyConstraint('state', 'batchId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coreData')
    op.drop_table('states')
    op.drop_table('batches')
    # ### end Alembic commands ###
