"""Add hospitalizedDischarged column

Revision ID: 58ea38a64c64
Revises: bc309f70af25
Create Date: 2021-01-12 15:41:17.174849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ea38a64c64'
down_revision = 'bc309f70af25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('hospitalizedDischarged', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coreData', 'hospitalizedDischarged')
    # ### end Alembic commands ###
