"""add covid19SiteTertiary

Revision ID: 595ca88a92f4
Revises: bbf03457c455
Create Date: 2020-06-08 10:21:58.046530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595ca88a92f4'
down_revision = 'bbf03457c455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('covid19SiteTertiary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'covid19SiteTertiary')
    # ### end Alembic commands ###
