"""new data dictionary columns

Revision ID: 65d9ed966b27
Revises: 0c6db53f2db2
Create Date: 2020-07-22 23:06:14.089886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d9ed966b27'
down_revision = '0c6db53f2db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('negativeAntibodyTests', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('negativeAntibodyTestsPeople', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('positiveAntibodyTests', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('positiveAntibodyTestsPeople', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('positiveAntigenTests', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('positiveAntigenTestsPeople', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('probableCases', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('totalAntibodyTests', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('totalAntibodyTestsPeople', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('totalAntigenTests', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('totalAntigenTestsPeople', sa.Integer(), nullable=True))
    op.add_column('coreData', sa.Column('totalTestEncountersViral', sa.Integer(), nullable=True))
    op.drop_column('states', 'fips')
    op.drop_column('states', 'pum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('pum', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('states', sa.Column('fips', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('coreData', 'totalTestEncountersViral')
    op.drop_column('coreData', 'totalAntigenTestsPeople')
    op.drop_column('coreData', 'totalAntigenTests')
    op.drop_column('coreData', 'totalAntibodyTestsPeople')
    op.drop_column('coreData', 'totalAntibodyTests')
    op.drop_column('coreData', 'probableCases')
    op.drop_column('coreData', 'positiveAntigenTestsPeople')
    op.drop_column('coreData', 'positiveAntigenTests')
    op.drop_column('coreData', 'positiveAntibodyTestsPeople')
    op.drop_column('coreData', 'positiveAntibodyTests')
    op.drop_column('coreData', 'negativeAntibodyTestsPeople')
    op.drop_column('coreData', 'negativeAntibodyTests')
    # ### end Alembic commands ###
