"""totalTestResults changes

Revision ID: 6dd1f6208644
Revises: cc91b057d1ee
Create Date: 2020-09-21 18:08:14.966610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd1f6208644'
down_revision = 'cc91b057d1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('states', sa.Column('totalTestResultsField', sa.String(), nullable=True))
    # set a default of posNeg for existing states to prevent null values. we'll import the full set of values manually
    op.add_column('states', sa.Column('totalTestResultsFieldDbColumn', sa.String(), nullable=False, server_default='posNeg'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'totalTestResultsFieldDbColumn')
    op.drop_column('states', 'totalTestResultsField')
    # ### end Alembic commands ###
