"""batch metadata

Revision ID: 7a2068644cd6
Revises: fc83a3cf66ba
Create Date: 2020-07-29 15:33:51.214242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2068644cd6'
down_revision = 'fc83a3cf66ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('link', sa.String(), nullable=True))
    op.add_column('batches', sa.Column('logCategory', sa.String(), nullable=True))
    op.add_column('batches', sa.Column('user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'user')
    op.drop_column('batches', 'logCategory')
    op.drop_column('batches', 'link')
    # ### end Alembic commands ###
