"""Remove unused positiveConfirmed column

Revision ID: 7b62c00f859e
Revises: 88af1a7d41dd
Create Date: 2020-09-29 11:55:20.496969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b62c00f859e'
down_revision = '88af1a7d41dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coreData', 'positiveConfirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('positiveConfirmed', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
