"""Adding edit diff info columns to batch

Revision ID: 88af1a7d41dd
Revises: 41ab3d22f073
Create Date: 2020-09-25 19:58:28.108088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88af1a7d41dd'
down_revision = '41ab3d22f073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('changedDates', sa.String(), nullable=True))
    op.add_column('batches', sa.Column('changedFields', sa.String(), nullable=True))
    op.add_column('batches', sa.Column('numRowsEdited', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'numRowsEdited')
    op.drop_column('batches', 'changedFields')
    op.drop_column('batches', 'changedDates')
    # ### end Alembic commands ###
