"""Remove batch changedDates in favor of a query

Revision ID: bc309f70af25
Revises: 7b62c00f859e
Create Date: 2020-10-04 01:41:17.292209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc309f70af25'
down_revision = '7b62c00f859e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'changedDates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('changedDates', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
