"""Renaming lastCheckTime to dateChecked for public API consistency

Revision ID: ee1eae7d2f16
Revises: da977436076c
Create Date: 2020-05-19 18:22:58.099785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee1eae7d2f16'
down_revision = 'da977436076c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('dateChecked', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('coreData', 'lastCheckTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('lastCheckTime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('coreData', 'dateChecked')
    # ### end Alembic commands ###
