"""antibody columns

Revision ID: fc83a3cf66ba
Revises: 65d9ed966b27
Create Date: 2020-07-23 21:07:48.724239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc83a3cf66ba'
down_revision = '65d9ed966b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coreData', 'antibodyPositive')
    op.drop_column('coreData', 'antibodyTotal')
    op.drop_column('coreData', 'antibodyNegative')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('antibodyNegative', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coreData', sa.Column('antibodyTotal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coreData', sa.Column('antibodyPositive', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
