"""Renaming dataDate to date

Revision ID: fea4af6bf9ce
Revises: 01f76bf60f51
Create Date: 2020-05-27 22:51:45.711845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fea4af6bf9ce'
down_revision = '01f76bf60f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('coreData', 'dataDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreData', sa.Column('dataDate', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('coreData', 'date')
    # ### end Alembic commands ###
